
const houseInfo=[{
    "id": "1",
    "houseName": "2026 40th ave sw",
    "price": "100,000",
    "bedrooms": "1",
    "bathrooms": "1",
    "sqft": "2000",
    "description": "This is a beautiful house in a great neighborhood.  It has a large backyard and a two car garage.",
    "image": "./Photos/house1.png",
    "noiseLevel": "3",
    "safety": "4",
    "walkability": "5",
    "petFriendly": "3",
    "airQuality": "4",
    "neighborhood": "4",
    "shopping": "5",
    "transportation": "4",
    "schoolsHighschool": "4",
    "schoolsMiddle": "4",
    "schoolsElementary": "4",
    "schoolsPreschool": "4",
    "pool": "no",
    "photos": ["./Photos/insideHouse1.png", "./Photos/insideHouse1-1.png"],
    "jackBooking": "yes",
    "jackFovorite": "yes",
    "timeOfBooking": "2020-03-20T00:01 PM",
    "lat" : "50.99082427487876",
    "lng" : "-114.11832951558249"
},
{
    "id": "2",
    "houseName": "8085 19th ave sw",
    "price": "200,000",
    "bedrooms": "2",
    "bathrooms": "2",
    "sqft": "2000",
    "description": "This is a beautiful house in a great neighborhood.  It has a large backyard and a one car garage.",
    "image": "./Photos/house2.png",
    "noiseLevel": "3",
    "safety": "4",
    "walkability": "5",
    "petFriendly": "3",
    "airQuality": "4",
    "neighborhood": "4",
    "shopping": "5",
    "transportation": "4",
    "schoolsHighschool": "4",
    "schoolsMiddle": "4",
    "schoolsElementary": "4",
    "schoolsPreschool": "4",
    "pool": "no",
    "photos": ["./Photos/insideHouse2.png", "./Photos/insideHouse2-1.png", "./Photos/insideHouse2-2.png"],
    "jackBooking": "yes",
    "jackFovorite": "yes",
    "timeOfBooking": "2020-03-20T00:00 PM",
    "lat" : "51.14722309638639",
    "lng" : "-114.07073863792215"
},
{
    "id": "3",
    "houseName": "2024 44th ave Nw",
    "price": "300,000",
    "bedrooms": "3",
    "bathrooms": "2",
    "sqft": "2000",
    "description": "This is a beautiful house in a great neighborhood.  It has a large backyard and a two car garage.",
    "image": "./Photos/house3.png",
    "noiseLevel": "3",
    "safety": "4",
    "walkability": "5",
    "petFriendly": "3",
    "airQuality": "4",
    "neighborhood": "4",
    "shopping": "5",
    "transportation": "4",
    "schoolsHighschool": "4",
    "schoolsMiddle": "4",
    "schoolsElementary": "4",
    "schoolsPreschool": "4",
    "pool": "yes",
    "photos": ["./Photos/insideHouse3.png", "./Photos/insideHouse3-1.png", "./Photos/insideHouse3-2.png"],
    "jackBooking": "no",
    "jackFovorite": "yes",
    "timeOfBooking": "NA",
    "lat" : "51.1001302774115",
    "lng" : "-114.26005033583782"

},
{
    "id": "4",
    "houseName": "10325 Bonaventure Dr SE, Calgary, AB T2J 5R8",
    "price": "400,000",
    "bedrooms": "3",
    "bathrooms": "2",
    "sqft": "2000",
    "description": "This is a beautiful house in a great neighborhood.  It has a large backyard and a two car garage.",
    "image": "./Photos/house4.png",
    "noiseLevel": "5",
    "safety": "3",
    "walkability": "5",
    "petFriendly": "3",
    "airQuality": "4",
    "neighborhood": "4",
    "shopping": "5",
    "transportation": "4",
    "schoolsHighschool": "4",
    "schoolsMiddle": "4",
    "schoolsElementary": "4",
    "schoolsPreschool": "4",
    "pool": "5",
    "photos": ["./Photos/insideHouse4.png", "./Photos/insideHouse4-1.png"],
    "jackBooking": "no",
    "jackFovorite": "no",
    "timeOfBooking": "NA",
    "lat" : "51.13212065795928",
    "lng" : "-114.25638624110948"
}, 

{
    "id": "5",
    "houseName": "1236 12 Ave SW, Calgary, AB T3C 1A7",
    "price": "600,000",
    "bedrooms": "5",
    "bathrooms": "4",
    "sqft": "2000",
    "description": "This is a beautiful house in a great neighborhood.  It has a large backyard and a two car garage.",
    "image": "./Photos/house4.png",
    "noiseLevel": "3",
    "safety": "4",
    "walkability": "5",
    "petFriendly": "3",
    "airQuality": "4",
    "neighborhood": "4",
    "shopping": "5",
    "transportation": "4",
    "schoolsHighschool": "4",
    "schoolsMiddle": "4",
    "schoolsElementary": "4",
    "schoolsPreschool": "4",
    "pool": "1",
    "photos": ["./Photos/insideHouse4.png", "./Photos/insideHouse4-1.png"],
    "jackBooking": "no",
    "jackFovorite": "no",
    "timeOfBooking": "NA",
    "lat" : "50.978671493187264",
    "lng" : "-114.08483295616112"
}, 

{
    "id": "6",
    "houseName": "1126 Memorial Dr NW, Calgary, AB T2N 3E3",
    "price": "700,000",
    "bedrooms": "3",
    "bathrooms": "2",
    "sqft": "2000",
    "description": "This is a beautiful house in a great neighborhood.  It has a large backyard and a two car garage.",
    "image": "./Photos/house4.png",
    "noiseLevel": "3",
    "safety": "5",
    "walkability": "5",
    "petFriendly": "3",
    "airQuality": "4",
    "neighborhood": "4",
    "shopping": "5",
    "transportation": "4",
    "schoolsHighschool": "4",
    "schoolsMiddle": "4",
    "schoolsElementary": "4",
    "schoolsPreschool": "4",
    "pool": "5",
    "photos": ["./Photos/insideHouse4.png", "./Photos/insideHouse4-1.png"],
    "jackBooking": "no",
    "jackFovorite": "no",
    "timeOfBooking": "NA",
    "lat" : "51.13232195619895",
    "lng" : "-114.16105060488393"
}, 

{
    "id": "7",
    "houseName": "315 8 Ave SW, Calgary, AB T2P 4K1",
    "price": "800,000",
    "bedrooms": "3",
    "bathrooms": "2",
    "sqft": "2000",
    "description": "This is a beautiful house in a great neighborhood.  It has a large backyard and a two car garage.",
    "image": "./Photos/house4.png",
    "noiseLevel": "4",
    "safety": "4",
    "walkability": "5",
    "petFriendly": "3",
    "airQuality": "4",
    "neighborhood": "4",
    "shopping": "5",
    "transportation": "2",
    "schoolsHighschool": "4",
    "schoolsMiddle": "4",
    "schoolsElementary": "4",
    "schoolsPreschool": "4",
    "pool": "no",
    "photos": ["./Photos/insideHouse4.png", "./Photos/insideHouse4-1.png"],
    "jackBooking": "no",
    "jackFovorite": "no",
    "timeOfBooking": "NA",
    "lat" : "51.03872490575816",
    "lng" : "-114.19126300609804"
}, 

{
    "id": "8",
    "houseName": "5920 Macleod Trail SW #100, Calgary, AB T2H 0K2",
    "price": "900,000",
    "bedrooms": "3",
    "bathrooms": "2",
    "sqft": "2000",
    "description": "This is a beautiful house in a great neighborhood.  It has a large backyard and a two car garage.",
    "image": "./Photos/house4.png",
    "noiseLevel": "3",
    "safety": "5",
    "walkability": "5",
    "petFriendly": "3",
    "airQuality": "4",
    "neighborhood": "4",
    "shopping": "5",
    "transportation": "1",
    "schoolsHighschool": "4",
    "schoolsMiddle": "4",
    "schoolsElementary": "4",
    "schoolsPreschool": "4",
    "pool": "5",
    "photos": ["./Photos/insideHouse4.png", "./Photos/insideHouse4-1.png"],
    "jackBooking": "no",
    "jackFovorite": "no",
    "timeOfBooking": "NA",
    "lat" : "50.969591917847644",
    "lng" : "-114.1253450398127"
}, 

{
    "id": "9",
    "houseName": "703 6 Ave SW #120, Calgary,",
    "price": "1,000,000",
    "bedrooms": "3",
    "bathrooms": "2",
    "sqft": "2000",
    "description": "This is a beautiful house in a great neighborhood.  It has a large backyard and a two car garage.",
    "image": "./Photos/house4.png",
    "noiseLevel": "3",
    "safety": "4",
    "walkability": "5",
    "petFriendly": "3",
    "airQuality": "4",
    "neighborhood": "4",
    "shopping": "5",
    "transportation": "4",
    "schoolsHighschool": "4",
    "schoolsMiddle": "4",
    "schoolsElementary": "4",
    "schoolsPreschool": "4",
    "pool": "5",
    "photos": ["./Photos/insideHouse4.png", "./Photos/insideHouse4-1.png"],
    "jackBooking": "no",
    "jackFovorite": "no",
    "timeOfBooking": "NA",
    "lat" : "51.02792966720807",
    "lng" : "-114.12122516691987"
}


]
export default houseInfo;
